# Generated by Django 3.2 on 2023-07-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_staff_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motions',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('startdatum', models.DateField(blank=True, null=True)),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('antragsteller_vorname', models.CharField(max_length=100)),
                ('antragsteller_nachname', models.CharField(max_length=100)),
                ('antragsteller_initialen', models.CharField(max_length=15)),
                ('edited', models.BooleanField(default=False)),
                ('bearbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Anträge',
                'ordering': ['antragsteller_nachname'],
            },
        ),
    ]
