# Generated by Django 3.2 on 2023-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desks',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
                ('client', models.CharField(max_length=50)),
                ('licence', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
