# Generated by Django 3.2 on 2023-01-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desks',
            options={'ordering': ['d_id'], 'verbose_name_plural': 'Arbeitsplätze'},
        ),
    ]
