# Generated by Django 3.2 on 2023-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_staff_aktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('s_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Mitteilungen',
                'ordering': ['datum'],
            },
        ),
    ]
