# Generated by Django 3.2 on 2023-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(default='b', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
